# BlackBoard/helm/templates/pvc.yaml
{{- if and .Values.redis.enabled .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-data
  labels:
    app.kubernetes.io/name: darwin-brain
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
{{- if .Values.sysadmin.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-gitops-data
  labels:
    app.kubernetes.io/name: darwin-brain
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gitops
spec:
  accessModes:
{{ toYaml .Values.sysadmin.persistence.accessModes | indent 4 }}
  {{- if .Values.sysadmin.persistence.storageClassName }}
  storageClassName: {{ .Values.sysadmin.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sysadmin.persistence.size }}
{{- end }}
